/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// AppLocationSettingStatus the model 'AppLocationSettingStatus'
type AppLocationSettingStatus string

// List of AppLocationSettingStatus
const (
	APPLOCATIONSETTINGSTATUS_PENDING     AppLocationSettingStatus = "pending"
	APPLOCATIONSETTINGSTATUS_CREATING    AppLocationSettingStatus = "creating"
	APPLOCATIONSETTINGSTATUS_UPDATING    AppLocationSettingStatus = "updating"
	APPLOCATIONSETTINGSTATUS_DELETING    AppLocationSettingStatus = "deleting"
	APPLOCATIONSETTINGSTATUS_UPSCALING   AppLocationSettingStatus = "upscaling"
	APPLOCATIONSETTINGSTATUS_DOWNSCALING AppLocationSettingStatus = "downscaling"
	APPLOCATIONSETTINGSTATUS_ERROR       AppLocationSettingStatus = "error"
	APPLOCATIONSETTINGSTATUS_READY       AppLocationSettingStatus = "ready"
	APPLOCATIONSETTINGSTATUS_WAITING     AppLocationSettingStatus = "waiting"
	APPLOCATIONSETTINGSTATUS_MOVING      AppLocationSettingStatus = "moving"
	APPLOCATIONSETTINGSTATUS_CLONING     AppLocationSettingStatus = "cloning"
)

// All allowed values of AppLocationSettingStatus enum
var AllowedAppLocationSettingStatusEnumValues = []AppLocationSettingStatus{
	"pending",
	"creating",
	"updating",
	"deleting",
	"upscaling",
	"downscaling",
	"error",
	"ready",
	"waiting",
	"moving",
	"cloning",
}

func (v *AppLocationSettingStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppLocationSettingStatus(value)
	for _, existing := range AllowedAppLocationSettingStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppLocationSettingStatus", value)
}

// NewAppLocationSettingStatusFromValue returns a pointer to a valid AppLocationSettingStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppLocationSettingStatusFromValue(v string) (*AppLocationSettingStatus, error) {
	ev := AppLocationSettingStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppLocationSettingStatus: valid values are %v", v, AllowedAppLocationSettingStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppLocationSettingStatus) IsValid() bool {
	for _, existing := range AllowedAppLocationSettingStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppLocationSettingStatus value
func (v AppLocationSettingStatus) Ptr() *AppLocationSettingStatus {
	return &v
}

type NullableAppLocationSettingStatus struct {
	value *AppLocationSettingStatus
	isSet bool
}

func (v NullableAppLocationSettingStatus) Get() *AppLocationSettingStatus {
	return v.value
}

func (v *NullableAppLocationSettingStatus) Set(val *AppLocationSettingStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAppLocationSettingStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAppLocationSettingStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppLocationSettingStatus(val *AppLocationSettingStatus) *NullableAppLocationSettingStatus {
	return &NullableAppLocationSettingStatus{value: val, isSet: true}
}

func (v NullableAppLocationSettingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppLocationSettingStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}