/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ServerConfigStatus the model 'ServerConfigStatus'
type ServerConfigStatus string

// List of ServerConfigStatus
const (
	SERVERCONFIGSTATUS_PENDING  ServerConfigStatus = "pending"
	SERVERCONFIGSTATUS_CREATING ServerConfigStatus = "creating"
	SERVERCONFIGSTATUS_UPDATING ServerConfigStatus = "updating"
	SERVERCONFIGSTATUS_DELETING ServerConfigStatus = "deleting"
	SERVERCONFIGSTATUS_WAITING  ServerConfigStatus = "waiting"
	SERVERCONFIGSTATUS_ERROR    ServerConfigStatus = "error"
	SERVERCONFIGSTATUS_READY    ServerConfigStatus = "ready"
)

// All allowed values of ServerConfigStatus enum
var AllowedServerConfigStatusEnumValues = []ServerConfigStatus{
	"pending",
	"creating",
	"updating",
	"deleting",
	"waiting",
	"error",
	"ready",
}

func (v *ServerConfigStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServerConfigStatus(value)
	for _, existing := range AllowedServerConfigStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ServerConfigStatus", value)
}

// NewServerConfigStatusFromValue returns a pointer to a valid ServerConfigStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServerConfigStatusFromValue(v string) (*ServerConfigStatus, error) {
	ev := ServerConfigStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServerConfigStatus: valid values are %v", v, AllowedServerConfigStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServerConfigStatus) IsValid() bool {
	for _, existing := range AllowedServerConfigStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ServerConfigStatus value
func (v ServerConfigStatus) Ptr() *ServerConfigStatus {
	return &v
}

type NullableServerConfigStatus struct {
	value *ServerConfigStatus
	isSet bool
}

func (v NullableServerConfigStatus) Get() *ServerConfigStatus {
	return v.value
}

func (v *NullableServerConfigStatus) Set(val *ServerConfigStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableServerConfigStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableServerConfigStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerConfigStatus(val *ServerConfigStatus) *NullableServerConfigStatus {
	return &NullableServerConfigStatus{value: val, isSet: true}
}

func (v NullableServerConfigStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerConfigStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}