/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DockerImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerImage{}

// DockerImage struct for DockerImage
type DockerImage struct {
	// The name of the docker image
	ImageName string `json:"imageName"`
	// The id of the registry to load the image
	RegistryId int32 `json:"registryId"`
	// Indicates whether the docker image is currently in use
	InUse bool `json:"inUse"`
}

type _DockerImage DockerImage

// NewDockerImage instantiates a new DockerImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerImage(imageName string, registryId int32, inUse bool) *DockerImage {
	this := DockerImage{}
	this.ImageName = imageName
	this.RegistryId = registryId
	this.InUse = inUse
	return &this
}

// NewDockerImageWithDefaults instantiates a new DockerImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerImageWithDefaults() *DockerImage {
	this := DockerImage{}
	return &this
}

// GetImageName returns the ImageName field value
func (o *DockerImage) GetImageName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageName
}

// GetImageNameOk returns a tuple with the ImageName field value
// and a boolean to check if the value has been set.
func (o *DockerImage) GetImageNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageName, true
}

// SetImageName sets field value
func (o *DockerImage) SetImageName(v string) {
	o.ImageName = v
}

// GetRegistryId returns the RegistryId field value
func (o *DockerImage) GetRegistryId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value
// and a boolean to check if the value has been set.
func (o *DockerImage) GetRegistryIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryId, true
}

// SetRegistryId sets field value
func (o *DockerImage) SetRegistryId(v int32) {
	o.RegistryId = v
}

// GetInUse returns the InUse field value
func (o *DockerImage) GetInUse() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InUse
}

// GetInUseOk returns a tuple with the InUse field value
// and a boolean to check if the value has been set.
func (o *DockerImage) GetInUseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InUse, true
}

// SetInUse sets field value
func (o *DockerImage) SetInUse(v bool) {
	o.InUse = v
}

func (o DockerImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageName"] = o.ImageName
	toSerialize["registryId"] = o.RegistryId
	toSerialize["inUse"] = o.InUse
	return toSerialize, nil
}

func (o *DockerImage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageName",
		"registryId",
		"inUse",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerImage := _DockerImage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerImage)

	if err != nil {
		return err
	}

	*o = DockerImage(varDockerImage)

	return err
}

type NullableDockerImage struct {
	value *DockerImage
	isSet bool
}

func (v NullableDockerImage) Get() *DockerImage {
	return v.value
}

func (v *NullableDockerImage) Set(val *DockerImage) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerImage) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerImage(val *DockerImage) *NullableDockerImage {
	return &NullableDockerImage{value: val, isSet: true}
}

func (v NullableDockerImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}