/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// SteamRuntime the model 'SteamRuntime'
type SteamRuntime string

// List of SteamRuntime
const (
	STEAMRUNTIME_SCOUT   SteamRuntime = "scout"
	STEAMRUNTIME_SOLDIER SteamRuntime = "soldier"
	STEAMRUNTIME_SNIPER  SteamRuntime = "sniper"
)

// All allowed values of SteamRuntime enum
var AllowedSteamRuntimeEnumValues = []SteamRuntime{
	"scout",
	"soldier",
	"sniper",
}

func (v *SteamRuntime) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SteamRuntime(value)
	for _, existing := range AllowedSteamRuntimeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SteamRuntime", value)
}

// NewSteamRuntimeFromValue returns a pointer to a valid SteamRuntime
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSteamRuntimeFromValue(v string) (*SteamRuntime, error) {
	ev := SteamRuntime(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SteamRuntime: valid values are %v", v, AllowedSteamRuntimeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SteamRuntime) IsValid() bool {
	for _, existing := range AllowedSteamRuntimeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SteamRuntime value
func (v SteamRuntime) Ptr() *SteamRuntime {
	return &v
}

type NullableSteamRuntime struct {
	value *SteamRuntime
	isSet bool
}

func (v NullableSteamRuntime) Get() *SteamRuntime {
	return v.value
}

func (v *NullableSteamRuntime) Set(val *SteamRuntime) {
	v.value = val
	v.isSet = true
}

func (v NullableSteamRuntime) IsSet() bool {
	return v.isSet
}

func (v *NullableSteamRuntime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSteamRuntime(val *SteamRuntime) *NullableSteamRuntime {
	return &NullableSteamRuntime{value: val, isSet: true}
}

func (v NullableSteamRuntime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSteamRuntime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}