/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SecretFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretFile{}

// SecretFile struct for SecretFile
type SecretFile struct {
	// The path in the container
	Target string `json:"target"`
	// The content of the secret file
	Content string `json:"content"`
}

type _SecretFile SecretFile

// NewSecretFile instantiates a new SecretFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretFile(target string, content string) *SecretFile {
	this := SecretFile{}
	this.Target = target
	this.Content = content
	return &this
}

// NewSecretFileWithDefaults instantiates a new SecretFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretFileWithDefaults() *SecretFile {
	this := SecretFile{}
	return &this
}

// GetTarget returns the Target field value
func (o *SecretFile) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *SecretFile) SetTarget(v string) {
	o.Target = v
}

// GetContent returns the Content field value
func (o *SecretFile) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SecretFile) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SecretFile) SetContent(v string) {
	o.Content = v
}

func (o SecretFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target"] = o.Target
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *SecretFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretFile := _SecretFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretFile)

	if err != nil {
		return err
	}

	*o = SecretFile(varSecretFile)

	return err
}

type NullableSecretFile struct {
	value *SecretFile
	isSet bool
}

func (v NullableSecretFile) Get() *SecretFile {
	return v.value
}

func (v *NullableSecretFile) Set(val *SecretFile) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretFile) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretFile(val *SecretFile) *NullableSecretFile {
	return &NullableSecretFile{value: val, isSet: true}
}

func (v NullableSecretFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}