/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SteamBranch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SteamBranch{}

// SteamBranch struct for SteamBranch
type SteamBranch struct {
	// The name of the branch
	Name string `json:"name"`
	// The unique identifier for the build
	Buildid NullableInt32 `json:"buildid"`
	// Indicates whether a password is required
	Pwdrequired NullableBool `json:"pwdrequired"`
	// A brief description of the build
	Description NullableString `json:"description"`
	// Last updated timestamp (in Unix epoch format)
	Timeupdated NullableInt32 `json:"timeupdated"`
}

type _SteamBranch SteamBranch

// NewSteamBranch instantiates a new SteamBranch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSteamBranch(name string, buildid NullableInt32, pwdrequired NullableBool, description NullableString, timeupdated NullableInt32) *SteamBranch {
	this := SteamBranch{}
	this.Name = name
	this.Buildid = buildid
	this.Pwdrequired = pwdrequired
	this.Description = description
	this.Timeupdated = timeupdated
	return &this
}

// NewSteamBranchWithDefaults instantiates a new SteamBranch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSteamBranchWithDefaults() *SteamBranch {
	this := SteamBranch{}
	return &this
}

// GetName returns the Name field value
func (o *SteamBranch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SteamBranch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SteamBranch) SetName(v string) {
	o.Name = v
}

// GetBuildid returns the Buildid field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *SteamBranch) GetBuildid() int32 {
	if o == nil || o.Buildid.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Buildid.Get()
}

// GetBuildidOk returns a tuple with the Buildid field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SteamBranch) GetBuildidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Buildid.Get(), o.Buildid.IsSet()
}

// SetBuildid sets field value
func (o *SteamBranch) SetBuildid(v int32) {
	o.Buildid.Set(&v)
}

// GetPwdrequired returns the Pwdrequired field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *SteamBranch) GetPwdrequired() bool {
	if o == nil || o.Pwdrequired.Get() == nil {
		var ret bool
		return ret
	}

	return *o.Pwdrequired.Get()
}

// GetPwdrequiredOk returns a tuple with the Pwdrequired field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SteamBranch) GetPwdrequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pwdrequired.Get(), o.Pwdrequired.IsSet()
}

// SetPwdrequired sets field value
func (o *SteamBranch) SetPwdrequired(v bool) {
	o.Pwdrequired.Set(&v)
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SteamBranch) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SteamBranch) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *SteamBranch) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetTimeupdated returns the Timeupdated field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *SteamBranch) GetTimeupdated() int32 {
	if o == nil || o.Timeupdated.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Timeupdated.Get()
}

// GetTimeupdatedOk returns a tuple with the Timeupdated field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SteamBranch) GetTimeupdatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeupdated.Get(), o.Timeupdated.IsSet()
}

// SetTimeupdated sets field value
func (o *SteamBranch) SetTimeupdated(v int32) {
	o.Timeupdated.Set(&v)
}

func (o SteamBranch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SteamBranch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["buildid"] = o.Buildid.Get()
	toSerialize["pwdrequired"] = o.Pwdrequired.Get()
	toSerialize["description"] = o.Description.Get()
	toSerialize["timeupdated"] = o.Timeupdated.Get()
	return toSerialize, nil
}

func (o *SteamBranch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"buildid",
		"pwdrequired",
		"description",
		"timeupdated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSteamBranch := _SteamBranch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSteamBranch)

	if err != nil {
		return err
	}

	*o = SteamBranch(varSteamBranch)

	return err
}

type NullableSteamBranch struct {
	value *SteamBranch
	isSet bool
}

func (v NullableSteamBranch) Get() *SteamBranch {
	return v.value
}

func (v *NullableSteamBranch) Set(val *SteamBranch) {
	v.value = val
	v.isSet = true
}

func (v NullableSteamBranch) IsSet() bool {
	return v.isSet
}

func (v *NullableSteamBranch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSteamBranch(val *SteamBranch) *NullableSteamBranch {
	return &NullableSteamBranch{value: val, isSet: true}
}

func (v NullableSteamBranch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSteamBranch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}