/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetDockerRegistries200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDockerRegistries200Response{}

// GetDockerRegistries200Response struct for GetDockerRegistries200Response
type GetDockerRegistries200Response struct {
	Data  []DockerRegistry                       `json:"data"`
	Links GetAppLocationSettings200ResponseLinks `json:"links"`
	Meta  GetAppLocationSettings200ResponseMeta  `json:"meta"`
}

type _GetDockerRegistries200Response GetDockerRegistries200Response

// NewGetDockerRegistries200Response instantiates a new GetDockerRegistries200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDockerRegistries200Response(data []DockerRegistry, links GetAppLocationSettings200ResponseLinks, meta GetAppLocationSettings200ResponseMeta) *GetDockerRegistries200Response {
	this := GetDockerRegistries200Response{}
	this.Data = data
	this.Links = links
	this.Meta = meta
	return &this
}

// NewGetDockerRegistries200ResponseWithDefaults instantiates a new GetDockerRegistries200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDockerRegistries200ResponseWithDefaults() *GetDockerRegistries200Response {
	this := GetDockerRegistries200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetDockerRegistries200Response) GetData() []DockerRegistry {
	if o == nil {
		var ret []DockerRegistry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetDockerRegistries200Response) GetDataOk() ([]DockerRegistry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetDockerRegistries200Response) SetData(v []DockerRegistry) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *GetDockerRegistries200Response) GetLinks() GetAppLocationSettings200ResponseLinks {
	if o == nil {
		var ret GetAppLocationSettings200ResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetDockerRegistries200Response) GetLinksOk() (*GetAppLocationSettings200ResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetDockerRegistries200Response) SetLinks(v GetAppLocationSettings200ResponseLinks) {
	o.Links = v
}

// GetMeta returns the Meta field value
func (o *GetDockerRegistries200Response) GetMeta() GetAppLocationSettings200ResponseMeta {
	if o == nil {
		var ret GetAppLocationSettings200ResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetDockerRegistries200Response) GetMetaOk() (*GetAppLocationSettings200ResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *GetDockerRegistries200Response) SetMeta(v GetAppLocationSettings200ResponseMeta) {
	o.Meta = v
}

func (o GetDockerRegistries200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDockerRegistries200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *GetDockerRegistries200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDockerRegistries200Response := _GetDockerRegistries200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDockerRegistries200Response)

	if err != nil {
		return err
	}

	*o = GetDockerRegistries200Response(varGetDockerRegistries200Response)

	return err
}

type NullableGetDockerRegistries200Response struct {
	value *GetDockerRegistries200Response
	isSet bool
}

func (v NullableGetDockerRegistries200Response) Get() *GetDockerRegistries200Response {
	return v.value
}

func (v *NullableGetDockerRegistries200Response) Set(val *GetDockerRegistries200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDockerRegistries200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDockerRegistries200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDockerRegistries200Response(val *GetDockerRegistries200Response) *NullableGetDockerRegistries200Response {
	return &NullableGetDockerRegistries200Response{value: val, isSet: true}
}

func (v NullableGetDockerRegistries200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDockerRegistries200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}