/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StoreDockerRegistryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreDockerRegistryRequest{}

// StoreDockerRegistryRequest struct for StoreDockerRegistryRequest
type StoreDockerRegistryRequest struct {
	// The type of the docker registry
	Type DockerRegistryType `json:"type"`
	// The name of the docker registry
	Name string `json:"name"`
	// The URL of the docker registry
	Url NullableString `json:"url,omitempty"`
	// The specific instance URL of the docker registry
	InstanceUrl NullableString `json:"instanceUrl,omitempty"`
	// The username to use for authentication
	Username NullableString `json:"username,omitempty"`
	// The access token to use for authentication
	AccessToken NullableString `json:"accessToken,omitempty"`
	// The password to use for authentication
	Password NullableString `json:"password,omitempty"`
	// Whether or not the registry is user-owned or organization-owned
	Organization *bool `json:"organization,omitempty"`
	// The AWS access key to use for authentication
	AwsAccessKey NullableString `json:"awsAccessKey,omitempty"`
	// The AWS secret access key to use for authentication
	AwsSecretAccessKey NullableString `json:"awsSecretAccessKey,omitempty"`
}

type _StoreDockerRegistryRequest StoreDockerRegistryRequest

// NewStoreDockerRegistryRequest instantiates a new StoreDockerRegistryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreDockerRegistryRequest(type_ DockerRegistryType, name string) *StoreDockerRegistryRequest {
	this := StoreDockerRegistryRequest{}
	this.Type = type_
	this.Name = name
	return &this
}

// NewStoreDockerRegistryRequestWithDefaults instantiates a new StoreDockerRegistryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreDockerRegistryRequestWithDefaults() *StoreDockerRegistryRequest {
	this := StoreDockerRegistryRequest{}
	return &this
}

// GetType returns the Type field value
func (o *StoreDockerRegistryRequest) GetType() DockerRegistryType {
	if o == nil {
		var ret DockerRegistryType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StoreDockerRegistryRequest) GetTypeOk() (*DockerRegistryType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StoreDockerRegistryRequest) SetType(v DockerRegistryType) {
	o.Type = v
}

// GetName returns the Name field value
func (o *StoreDockerRegistryRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StoreDockerRegistryRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StoreDockerRegistryRequest) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *StoreDockerRegistryRequest) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *StoreDockerRegistryRequest) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetUrl() {
	o.Url.Unset()
}

// GetInstanceUrl returns the InstanceUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetInstanceUrl() string {
	if o == nil || IsNil(o.InstanceUrl.Get()) {
		var ret string
		return ret
	}
	return *o.InstanceUrl.Get()
}

// GetInstanceUrlOk returns a tuple with the InstanceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetInstanceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstanceUrl.Get(), o.InstanceUrl.IsSet()
}

// HasInstanceUrl returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasInstanceUrl() bool {
	if o != nil && o.InstanceUrl.IsSet() {
		return true
	}

	return false
}

// SetInstanceUrl gets a reference to the given NullableString and assigns it to the InstanceUrl field.
func (o *StoreDockerRegistryRequest) SetInstanceUrl(v string) {
	o.InstanceUrl.Set(&v)
}
// SetInstanceUrlNil sets the value for InstanceUrl to be an explicit nil
func (o *StoreDockerRegistryRequest) SetInstanceUrlNil() {
	o.InstanceUrl.Set(nil)
}

// UnsetInstanceUrl ensures that no value is present for InstanceUrl, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetInstanceUrl() {
	o.InstanceUrl.Unset()
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetUsername() string {
	if o == nil || IsNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *StoreDockerRegistryRequest) SetUsername(v string) {
	o.Username.Set(&v)
}
// SetUsernameNil sets the value for Username to be an explicit nil
func (o *StoreDockerRegistryRequest) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetUsername() {
	o.Username.Unset()
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken.Get()) {
		var ret string
		return ret
	}
	return *o.AccessToken.Get()
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessToken.Get(), o.AccessToken.IsSet()
}

// HasAccessToken returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasAccessToken() bool {
	if o != nil && o.AccessToken.IsSet() {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given NullableString and assigns it to the AccessToken field.
func (o *StoreDockerRegistryRequest) SetAccessToken(v string) {
	o.AccessToken.Set(&v)
}
// SetAccessTokenNil sets the value for AccessToken to be an explicit nil
func (o *StoreDockerRegistryRequest) SetAccessTokenNil() {
	o.AccessToken.Set(nil)
}

// UnsetAccessToken ensures that no value is present for AccessToken, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetAccessToken() {
	o.AccessToken.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *StoreDockerRegistryRequest) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *StoreDockerRegistryRequest) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetPassword() {
	o.Password.Unset()
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *StoreDockerRegistryRequest) GetOrganization() bool {
	if o == nil || IsNil(o.Organization) {
		var ret bool
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreDockerRegistryRequest) GetOrganizationOk() (*bool, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given bool and assigns it to the Organization field.
func (o *StoreDockerRegistryRequest) SetOrganization(v bool) {
	o.Organization = &v
}

// GetAwsAccessKey returns the AwsAccessKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetAwsAccessKey() string {
	if o == nil || IsNil(o.AwsAccessKey.Get()) {
		var ret string
		return ret
	}
	return *o.AwsAccessKey.Get()
}

// GetAwsAccessKeyOk returns a tuple with the AwsAccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetAwsAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsAccessKey.Get(), o.AwsAccessKey.IsSet()
}

// HasAwsAccessKey returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasAwsAccessKey() bool {
	if o != nil && o.AwsAccessKey.IsSet() {
		return true
	}

	return false
}

// SetAwsAccessKey gets a reference to the given NullableString and assigns it to the AwsAccessKey field.
func (o *StoreDockerRegistryRequest) SetAwsAccessKey(v string) {
	o.AwsAccessKey.Set(&v)
}
// SetAwsAccessKeyNil sets the value for AwsAccessKey to be an explicit nil
func (o *StoreDockerRegistryRequest) SetAwsAccessKeyNil() {
	o.AwsAccessKey.Set(nil)
}

// UnsetAwsAccessKey ensures that no value is present for AwsAccessKey, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetAwsAccessKey() {
	o.AwsAccessKey.Unset()
}

// GetAwsSecretAccessKey returns the AwsSecretAccessKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreDockerRegistryRequest) GetAwsSecretAccessKey() string {
	if o == nil || IsNil(o.AwsSecretAccessKey.Get()) {
		var ret string
		return ret
	}
	return *o.AwsSecretAccessKey.Get()
}

// GetAwsSecretAccessKeyOk returns a tuple with the AwsSecretAccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreDockerRegistryRequest) GetAwsSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsSecretAccessKey.Get(), o.AwsSecretAccessKey.IsSet()
}

// HasAwsSecretAccessKey returns a boolean if a field has been set.
func (o *StoreDockerRegistryRequest) HasAwsSecretAccessKey() bool {
	if o != nil && o.AwsSecretAccessKey.IsSet() {
		return true
	}

	return false
}

// SetAwsSecretAccessKey gets a reference to the given NullableString and assigns it to the AwsSecretAccessKey field.
func (o *StoreDockerRegistryRequest) SetAwsSecretAccessKey(v string) {
	o.AwsSecretAccessKey.Set(&v)
}
// SetAwsSecretAccessKeyNil sets the value for AwsSecretAccessKey to be an explicit nil
func (o *StoreDockerRegistryRequest) SetAwsSecretAccessKeyNil() {
	o.AwsSecretAccessKey.Set(nil)
}

// UnsetAwsSecretAccessKey ensures that no value is present for AwsSecretAccessKey, not even an explicit nil
func (o *StoreDockerRegistryRequest) UnsetAwsSecretAccessKey() {
	o.AwsSecretAccessKey.Unset()
}

func (o StoreDockerRegistryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreDockerRegistryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	if o.InstanceUrl.IsSet() {
		toSerialize["instanceUrl"] = o.InstanceUrl.Get()
	}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if o.AccessToken.IsSet() {
		toSerialize["accessToken"] = o.AccessToken.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if o.AwsAccessKey.IsSet() {
		toSerialize["awsAccessKey"] = o.AwsAccessKey.Get()
	}
	if o.AwsSecretAccessKey.IsSet() {
		toSerialize["awsSecretAccessKey"] = o.AwsSecretAccessKey.Get()
	}
	return toSerialize, nil
}

func (o *StoreDockerRegistryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreDockerRegistryRequest := _StoreDockerRegistryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreDockerRegistryRequest)

	if err != nil {
		return err
	}

	*o = StoreDockerRegistryRequest(varStoreDockerRegistryRequest)

	return err
}

type NullableStoreDockerRegistryRequest struct {
	value *StoreDockerRegistryRequest
	isSet bool
}

func (v NullableStoreDockerRegistryRequest) Get() *StoreDockerRegistryRequest {
	return v.value
}

func (v *NullableStoreDockerRegistryRequest) Set(val *StoreDockerRegistryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreDockerRegistryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreDockerRegistryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreDockerRegistryRequest(val *StoreDockerRegistryRequest) *NullableStoreDockerRegistryRequest {
	return &NullableStoreDockerRegistryRequest{value: val, isSet: true}
}

func (v NullableStoreDockerRegistryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreDockerRegistryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}