/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Location type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Location{}

// Location struct for Location
type Location struct {
	// The name of the city
	City string `json:"city"`
	// The display-friendly name of the city
	CityDisplay string `json:"cityDisplay"`
	// The continent name
	Continent string `json:"continent"`
	// The country name
	Country string `json:"country"`
	// Indicates if the location is password protected
	IsProtected bool `json:"isProtected"`
}

type _Location Location

// NewLocation instantiates a new Location object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocation(city string, cityDisplay string, continent string, country string, isProtected bool) *Location {
	this := Location{}
	this.City = city
	this.CityDisplay = cityDisplay
	this.Continent = continent
	this.Country = country
	this.IsProtected = isProtected
	return &this
}

// NewLocationWithDefaults instantiates a new Location object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationWithDefaults() *Location {
	this := Location{}
	return &this
}

// GetCity returns the City field value
func (o *Location) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *Location) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *Location) SetCity(v string) {
	o.City = v
}

// GetCityDisplay returns the CityDisplay field value
func (o *Location) GetCityDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CityDisplay
}

// GetCityDisplayOk returns a tuple with the CityDisplay field value
// and a boolean to check if the value has been set.
func (o *Location) GetCityDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CityDisplay, true
}

// SetCityDisplay sets field value
func (o *Location) SetCityDisplay(v string) {
	o.CityDisplay = v
}

// GetContinent returns the Continent field value
func (o *Location) GetContinent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Continent
}

// GetContinentOk returns a tuple with the Continent field value
// and a boolean to check if the value has been set.
func (o *Location) GetContinentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Continent, true
}

// SetContinent sets field value
func (o *Location) SetContinent(v string) {
	o.Continent = v
}

// GetCountry returns the Country field value
func (o *Location) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *Location) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *Location) SetCountry(v string) {
	o.Country = v
}

// GetIsProtected returns the IsProtected field value
func (o *Location) GetIsProtected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsProtected
}

// GetIsProtectedOk returns a tuple with the IsProtected field value
// and a boolean to check if the value has been set.
func (o *Location) GetIsProtectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsProtected, true
}

// SetIsProtected sets field value
func (o *Location) SetIsProtected(v bool) {
	o.IsProtected = v
}

func (o Location) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Location) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["city"] = o.City
	toSerialize["cityDisplay"] = o.CityDisplay
	toSerialize["continent"] = o.Continent
	toSerialize["country"] = o.Country
	toSerialize["isProtected"] = o.IsProtected
	return toSerialize, nil
}

func (o *Location) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"city",
		"cityDisplay",
		"continent",
		"country",
		"isProtected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocation := _Location{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocation)

	if err != nil {
		return err
	}

	*o = Location(varLocation)

	return err
}

type NullableLocation struct {
	value *Location
	isSet bool
}

func (v NullableLocation) Get() *Location {
	return v.value
}

func (v *NullableLocation) Set(val *Location) {
	v.value = val
	v.isSet = true
}

func (v NullableLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocation(val *Location) *NullableLocation {
	return &NullableLocation{value: val, isSet: true}
}

func (v NullableLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}