/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateUpdateSteam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUpdateSteam{}

// CreateUpdateSteam struct for CreateUpdateSteam
type CreateUpdateSteam struct {
	// The Steam App ID
	SteamAppId int32 `json:"steamAppId"`
	// The branch to use
	Branch string `json:"branch"`
	// The password to use
	Password NullableString `json:"password"`
	// The command to execute
	Command string `json:"command"`
	// The steam account username
	SteamcmdUsername NullableString `json:"steamcmdUsername"`
	// The steam account password
	SteamcmdPassword NullableString `json:"steamcmdPassword"`
	// Whether or not the binary needs a graphical interface
	Headful bool `json:"headful"`
	// Whether or not the the license agreement needs to be requested
	RequestLicense bool `json:"requestLicense"`
	// The steam runtime the server depends on
	Runtime SteamRuntime `json:"runtime"`
	// A space-separated list of additional packages to install
	AdditionalPackages NullableString `json:"additionalPackages"`
	// Whether or not the steamworks app is unpublished or published
	Unpublished bool `json:"unpublished"`
}

type _CreateUpdateSteam CreateUpdateSteam

// NewCreateUpdateSteam instantiates a new CreateUpdateSteam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUpdateSteam(steamAppId int32, branch string, password NullableString, command string, steamcmdUsername NullableString, steamcmdPassword NullableString, headful bool, requestLicense bool, runtime SteamRuntime, additionalPackages NullableString, unpublished bool) *CreateUpdateSteam {
	this := CreateUpdateSteam{}
	this.SteamAppId = steamAppId
	this.Branch = branch
	this.Password = password
	this.Command = command
	this.SteamcmdUsername = steamcmdUsername
	this.SteamcmdPassword = steamcmdPassword
	this.Headful = headful
	this.RequestLicense = requestLicense
	this.Runtime = runtime
	this.AdditionalPackages = additionalPackages
	this.Unpublished = unpublished
	return &this
}

// NewCreateUpdateSteamWithDefaults instantiates a new CreateUpdateSteam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUpdateSteamWithDefaults() *CreateUpdateSteam {
	this := CreateUpdateSteam{}
	return &this
}

// GetSteamAppId returns the SteamAppId field value
func (o *CreateUpdateSteam) GetSteamAppId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SteamAppId
}

// GetSteamAppIdOk returns a tuple with the SteamAppId field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetSteamAppIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SteamAppId, true
}

// SetSteamAppId sets field value
func (o *CreateUpdateSteam) SetSteamAppId(v int32) {
	o.SteamAppId = v
}

// GetBranch returns the Branch field value
func (o *CreateUpdateSteam) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *CreateUpdateSteam) SetBranch(v string) {
	o.Branch = v
}

// GetPassword returns the Password field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateUpdateSteam) GetPassword() string {
	if o == nil || o.Password.Get() == nil {
		var ret string
		return ret
	}

	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateSteam) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// SetPassword sets field value
func (o *CreateUpdateSteam) SetPassword(v string) {
	o.Password.Set(&v)
}

// GetCommand returns the Command field value
func (o *CreateUpdateSteam) GetCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *CreateUpdateSteam) SetCommand(v string) {
	o.Command = v
}

// GetSteamcmdUsername returns the SteamcmdUsername field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateUpdateSteam) GetSteamcmdUsername() string {
	if o == nil || o.SteamcmdUsername.Get() == nil {
		var ret string
		return ret
	}

	return *o.SteamcmdUsername.Get()
}

// GetSteamcmdUsernameOk returns a tuple with the SteamcmdUsername field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateSteam) GetSteamcmdUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SteamcmdUsername.Get(), o.SteamcmdUsername.IsSet()
}

// SetSteamcmdUsername sets field value
func (o *CreateUpdateSteam) SetSteamcmdUsername(v string) {
	o.SteamcmdUsername.Set(&v)
}

// GetSteamcmdPassword returns the SteamcmdPassword field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateUpdateSteam) GetSteamcmdPassword() string {
	if o == nil || o.SteamcmdPassword.Get() == nil {
		var ret string
		return ret
	}

	return *o.SteamcmdPassword.Get()
}

// GetSteamcmdPasswordOk returns a tuple with the SteamcmdPassword field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateSteam) GetSteamcmdPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SteamcmdPassword.Get(), o.SteamcmdPassword.IsSet()
}

// SetSteamcmdPassword sets field value
func (o *CreateUpdateSteam) SetSteamcmdPassword(v string) {
	o.SteamcmdPassword.Set(&v)
}

// GetHeadful returns the Headful field value
func (o *CreateUpdateSteam) GetHeadful() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Headful
}

// GetHeadfulOk returns a tuple with the Headful field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetHeadfulOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Headful, true
}

// SetHeadful sets field value
func (o *CreateUpdateSteam) SetHeadful(v bool) {
	o.Headful = v
}

// GetRequestLicense returns the RequestLicense field value
func (o *CreateUpdateSteam) GetRequestLicense() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequestLicense
}

// GetRequestLicenseOk returns a tuple with the RequestLicense field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetRequestLicenseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestLicense, true
}

// SetRequestLicense sets field value
func (o *CreateUpdateSteam) SetRequestLicense(v bool) {
	o.RequestLicense = v
}

// GetRuntime returns the Runtime field value
func (o *CreateUpdateSteam) GetRuntime() SteamRuntime {
	if o == nil {
		var ret SteamRuntime
		return ret
	}

	return o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetRuntimeOk() (*SteamRuntime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runtime, true
}

// SetRuntime sets field value
func (o *CreateUpdateSteam) SetRuntime(v SteamRuntime) {
	o.Runtime = v
}

// GetAdditionalPackages returns the AdditionalPackages field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateUpdateSteam) GetAdditionalPackages() string {
	if o == nil || o.AdditionalPackages.Get() == nil {
		var ret string
		return ret
	}

	return *o.AdditionalPackages.Get()
}

// GetAdditionalPackagesOk returns a tuple with the AdditionalPackages field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateUpdateSteam) GetAdditionalPackagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdditionalPackages.Get(), o.AdditionalPackages.IsSet()
}

// SetAdditionalPackages sets field value
func (o *CreateUpdateSteam) SetAdditionalPackages(v string) {
	o.AdditionalPackages.Set(&v)
}

// GetUnpublished returns the Unpublished field value
func (o *CreateUpdateSteam) GetUnpublished() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Unpublished
}

// GetUnpublishedOk returns a tuple with the Unpublished field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSteam) GetUnpublishedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unpublished, true
}

// SetUnpublished sets field value
func (o *CreateUpdateSteam) SetUnpublished(v bool) {
	o.Unpublished = v
}

func (o CreateUpdateSteam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUpdateSteam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["steamAppId"] = o.SteamAppId
	toSerialize["branch"] = o.Branch
	toSerialize["password"] = o.Password.Get()
	toSerialize["command"] = o.Command
	toSerialize["steamcmdUsername"] = o.SteamcmdUsername.Get()
	toSerialize["steamcmdPassword"] = o.SteamcmdPassword.Get()
	toSerialize["headful"] = o.Headful
	toSerialize["requestLicense"] = o.RequestLicense
	toSerialize["runtime"] = o.Runtime
	toSerialize["additionalPackages"] = o.AdditionalPackages.Get()
	toSerialize["unpublished"] = o.Unpublished
	return toSerialize, nil
}

func (o *CreateUpdateSteam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"steamAppId",
		"branch",
		"password",
		"command",
		"steamcmdUsername",
		"steamcmdPassword",
		"headful",
		"requestLicense",
		"runtime",
		"additionalPackages",
		"unpublished",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUpdateSteam := _CreateUpdateSteam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUpdateSteam)

	if err != nil {
		return err
	}

	*o = CreateUpdateSteam(varCreateUpdateSteam)

	return err
}

type NullableCreateUpdateSteam struct {
	value *CreateUpdateSteam
	isSet bool
}

func (v NullableCreateUpdateSteam) Get() *CreateUpdateSteam {
	return v.value
}

func (v *NullableCreateUpdateSteam) Set(val *CreateUpdateSteam) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUpdateSteam) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUpdateSteam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUpdateSteam(val *CreateUpdateSteam) *NullableCreateUpdateSteam {
	return &NullableCreateUpdateSteam{value: val, isSet: true}
}

func (v NullableCreateUpdateSteam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUpdateSteam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}