/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Backup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Backup{}

// Backup struct for Backup
type Backup struct {
	// The name of the backup
	Name string `json:"name"`
	// The name of the stored archive
	ArchiveName string `json:"archiveName"`
	// The timestamp of the backups creation
	CreatedAt time.Time `json:"createdAt"`
	// The timestamp of when the backup was restored, null if not restored
	RestoredAt NullableTime `json:"restoredAt"`
}

type _Backup Backup

// NewBackup instantiates a new Backup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackup(name string, archiveName string, createdAt time.Time, restoredAt NullableTime) *Backup {
	this := Backup{}
	this.Name = name
	this.ArchiveName = archiveName
	this.CreatedAt = createdAt
	this.RestoredAt = restoredAt
	return &this
}

// NewBackupWithDefaults instantiates a new Backup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupWithDefaults() *Backup {
	this := Backup{}
	return &this
}

// GetName returns the Name field value
func (o *Backup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Backup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Backup) SetName(v string) {
	o.Name = v
}

// GetArchiveName returns the ArchiveName field value
func (o *Backup) GetArchiveName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArchiveName
}

// GetArchiveNameOk returns a tuple with the ArchiveName field value
// and a boolean to check if the value has been set.
func (o *Backup) GetArchiveNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArchiveName, true
}

// SetArchiveName sets field value
func (o *Backup) SetArchiveName(v string) {
	o.ArchiveName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Backup) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Backup) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Backup) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRestoredAt returns the RestoredAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Backup) GetRestoredAt() time.Time {
	if o == nil || o.RestoredAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.RestoredAt.Get()
}

// GetRestoredAtOk returns a tuple with the RestoredAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Backup) GetRestoredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RestoredAt.Get(), o.RestoredAt.IsSet()
}

// SetRestoredAt sets field value
func (o *Backup) SetRestoredAt(v time.Time) {
	o.RestoredAt.Set(&v)
}

func (o Backup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Backup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["archiveName"] = o.ArchiveName
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["restoredAt"] = o.RestoredAt.Get()
	return toSerialize, nil
}

func (o *Backup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"archiveName",
		"createdAt",
		"restoredAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackup := _Backup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackup)

	if err != nil {
		return err
	}

	*o = Backup(varBackup)

	return err
}

type NullableBackup struct {
	value *Backup
	isSet bool
}

func (v NullableBackup) Get() *Backup {
	return v.value
}

func (v *NullableBackup) Set(val *Backup) {
	v.value = val
	v.isSet = true
}

func (v NullableBackup) IsSet() bool {
	return v.isSet
}

func (v *NullableBackup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackup(val *Backup) *NullableBackup {
	return &NullableBackup{value: val, isSet: true}
}

func (v NullableBackup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}