/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StoreAppRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreAppRequest{}

// StoreAppRequest struct for StoreAppRequest
type StoreAppRequest struct {
	// The name of the app
	Name string `json:"name"`
}

type _StoreAppRequest StoreAppRequest

// NewStoreAppRequest instantiates a new StoreAppRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreAppRequest(name string) *StoreAppRequest {
	this := StoreAppRequest{}
	this.Name = name
	return &this
}

// NewStoreAppRequestWithDefaults instantiates a new StoreAppRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreAppRequestWithDefaults() *StoreAppRequest {
	this := StoreAppRequest{}
	return &this
}

// GetName returns the Name field value
func (o *StoreAppRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StoreAppRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StoreAppRequest) SetName(v string) {
	o.Name = v
}

func (o StoreAppRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreAppRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *StoreAppRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreAppRequest := _StoreAppRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreAppRequest)

	if err != nil {
		return err
	}

	*o = StoreAppRequest(varStoreAppRequest)

	return err
}

type NullableStoreAppRequest struct {
	value *StoreAppRequest
	isSet bool
}

func (v NullableStoreAppRequest) Get() *StoreAppRequest {
	return v.value
}

func (v *NullableStoreAppRequest) Set(val *StoreAppRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreAppRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreAppRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreAppRequest(val *StoreAppRequest) *NullableStoreAppRequest {
	return &NullableStoreAppRequest{value: val, isSet: true}
}

func (v NullableStoreAppRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreAppRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}