/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AppLocationSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppLocationSetting{}

// AppLocationSetting struct for AppLocationSetting
type AppLocationSetting struct {
	// The id of the app location setting
	Id int32 `json:"id"`
	// The name of the app location setting
	Name string `json:"name"`
	// The app id of the app location setting
	AppId int32 `json:"appId"`
	// The server config id of the app location setting
	ServerConfigId int32 `json:"serverConfigId"`
	// The number of instances that should run at the specific location
	NumInstances int32 `json:"numInstances"`
	// Whether the auto scaler is enabled
	AutoScalerEnabled bool `json:"autoScalerEnabled"`
	// The minimum number of instances that should run at the specific location
	AutoScalerMin *int32 `json:"autoScalerMin,omitempty"`
	// The maximum number of instances that should run at the specific location
	AutoScalerMax *int32 `json:"autoScalerMax,omitempty"`
	// The current status
	Status AppLocationSettingStatus `json:"status"`
	// An optional message
	StatusMessage NullableString `json:"statusMessage"`
	// Indicates if the app location setting is under maintenance
	Maintenance bool `json:"maintenance"`
	// Indicates whether the app location setting is currently in use
	InUse bool `json:"inUse"`
	// The placement to use
	Placement Placement `json:"placement"`
	// The server config to use
	ServerConfig *ServerConfig `json:"serverConfig,omitempty"`
}

type _AppLocationSetting AppLocationSetting

// NewAppLocationSetting instantiates a new AppLocationSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppLocationSetting(id int32, name string, appId int32, serverConfigId int32, numInstances int32, autoScalerEnabled bool, status AppLocationSettingStatus, statusMessage NullableString, maintenance bool, inUse bool, placement Placement) *AppLocationSetting {
	this := AppLocationSetting{}
	this.Id = id
	this.Name = name
	this.AppId = appId
	this.ServerConfigId = serverConfigId
	this.NumInstances = numInstances
	this.AutoScalerEnabled = autoScalerEnabled
	this.Status = status
	this.StatusMessage = statusMessage
	this.Maintenance = maintenance
	this.InUse = inUse
	this.Placement = placement
	return &this
}

// NewAppLocationSettingWithDefaults instantiates a new AppLocationSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppLocationSettingWithDefaults() *AppLocationSetting {
	this := AppLocationSetting{}
	return &this
}

// GetId returns the Id field value
func (o *AppLocationSetting) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppLocationSetting) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AppLocationSetting) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppLocationSetting) SetName(v string) {
	o.Name = v
}

// GetAppId returns the AppId field value
func (o *AppLocationSetting) GetAppId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetAppIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *AppLocationSetting) SetAppId(v int32) {
	o.AppId = v
}

// GetServerConfigId returns the ServerConfigId field value
func (o *AppLocationSetting) GetServerConfigId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServerConfigId
}

// GetServerConfigIdOk returns a tuple with the ServerConfigId field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetServerConfigIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerConfigId, true
}

// SetServerConfigId sets field value
func (o *AppLocationSetting) SetServerConfigId(v int32) {
	o.ServerConfigId = v
}

// GetNumInstances returns the NumInstances field value
func (o *AppLocationSetting) GetNumInstances() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumInstances
}

// GetNumInstancesOk returns a tuple with the NumInstances field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetNumInstancesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumInstances, true
}

// SetNumInstances sets field value
func (o *AppLocationSetting) SetNumInstances(v int32) {
	o.NumInstances = v
}

// GetAutoScalerEnabled returns the AutoScalerEnabled field value
func (o *AppLocationSetting) GetAutoScalerEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoScalerEnabled
}

// GetAutoScalerEnabledOk returns a tuple with the AutoScalerEnabled field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetAutoScalerEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoScalerEnabled, true
}

// SetAutoScalerEnabled sets field value
func (o *AppLocationSetting) SetAutoScalerEnabled(v bool) {
	o.AutoScalerEnabled = v
}

// GetAutoScalerMin returns the AutoScalerMin field value if set, zero value otherwise.
func (o *AppLocationSetting) GetAutoScalerMin() int32 {
	if o == nil || IsNil(o.AutoScalerMin) {
		var ret int32
		return ret
	}
	return *o.AutoScalerMin
}

// GetAutoScalerMinOk returns a tuple with the AutoScalerMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetAutoScalerMinOk() (*int32, bool) {
	if o == nil || IsNil(o.AutoScalerMin) {
		return nil, false
	}
	return o.AutoScalerMin, true
}

// HasAutoScalerMin returns a boolean if a field has been set.
func (o *AppLocationSetting) HasAutoScalerMin() bool {
	if o != nil && !IsNil(o.AutoScalerMin) {
		return true
	}

	return false
}

// SetAutoScalerMin gets a reference to the given int32 and assigns it to the AutoScalerMin field.
func (o *AppLocationSetting) SetAutoScalerMin(v int32) {
	o.AutoScalerMin = &v
}

// GetAutoScalerMax returns the AutoScalerMax field value if set, zero value otherwise.
func (o *AppLocationSetting) GetAutoScalerMax() int32 {
	if o == nil || IsNil(o.AutoScalerMax) {
		var ret int32
		return ret
	}
	return *o.AutoScalerMax
}

// GetAutoScalerMaxOk returns a tuple with the AutoScalerMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetAutoScalerMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.AutoScalerMax) {
		return nil, false
	}
	return o.AutoScalerMax, true
}

// HasAutoScalerMax returns a boolean if a field has been set.
func (o *AppLocationSetting) HasAutoScalerMax() bool {
	if o != nil && !IsNil(o.AutoScalerMax) {
		return true
	}

	return false
}

// SetAutoScalerMax gets a reference to the given int32 and assigns it to the AutoScalerMax field.
func (o *AppLocationSetting) SetAutoScalerMax(v int32) {
	o.AutoScalerMax = &v
}

// GetStatus returns the Status field value
func (o *AppLocationSetting) GetStatus() AppLocationSettingStatus {
	if o == nil {
		var ret AppLocationSettingStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetStatusOk() (*AppLocationSettingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AppLocationSetting) SetStatus(v AppLocationSettingStatus) {
	o.Status = v
}

// GetStatusMessage returns the StatusMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AppLocationSetting) GetStatusMessage() string {
	if o == nil || o.StatusMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.StatusMessage.Get()
}

// GetStatusMessageOk returns a tuple with the StatusMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppLocationSetting) GetStatusMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusMessage.Get(), o.StatusMessage.IsSet()
}

// SetStatusMessage sets field value
func (o *AppLocationSetting) SetStatusMessage(v string) {
	o.StatusMessage.Set(&v)
}

// GetMaintenance returns the Maintenance field value
func (o *AppLocationSetting) GetMaintenance() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Maintenance
}

// GetMaintenanceOk returns a tuple with the Maintenance field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetMaintenanceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Maintenance, true
}

// SetMaintenance sets field value
func (o *AppLocationSetting) SetMaintenance(v bool) {
	o.Maintenance = v
}

// GetInUse returns the InUse field value
func (o *AppLocationSetting) GetInUse() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InUse
}

// GetInUseOk returns a tuple with the InUse field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetInUseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InUse, true
}

// SetInUse sets field value
func (o *AppLocationSetting) SetInUse(v bool) {
	o.InUse = v
}

// GetPlacement returns the Placement field value
func (o *AppLocationSetting) GetPlacement() Placement {
	if o == nil {
		var ret Placement
		return ret
	}

	return o.Placement
}

// GetPlacementOk returns a tuple with the Placement field value
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetPlacementOk() (*Placement, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Placement, true
}

// SetPlacement sets field value
func (o *AppLocationSetting) SetPlacement(v Placement) {
	o.Placement = v
}

// GetServerConfig returns the ServerConfig field value if set, zero value otherwise.
func (o *AppLocationSetting) GetServerConfig() ServerConfig {
	if o == nil || IsNil(o.ServerConfig) {
		var ret ServerConfig
		return ret
	}
	return *o.ServerConfig
}

// GetServerConfigOk returns a tuple with the ServerConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLocationSetting) GetServerConfigOk() (*ServerConfig, bool) {
	if o == nil || IsNil(o.ServerConfig) {
		return nil, false
	}
	return o.ServerConfig, true
}

// HasServerConfig returns a boolean if a field has been set.
func (o *AppLocationSetting) HasServerConfig() bool {
	if o != nil && !IsNil(o.ServerConfig) {
		return true
	}

	return false
}

// SetServerConfig gets a reference to the given ServerConfig and assigns it to the ServerConfig field.
func (o *AppLocationSetting) SetServerConfig(v ServerConfig) {
	o.ServerConfig = &v
}

func (o AppLocationSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppLocationSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["appId"] = o.AppId
	toSerialize["serverConfigId"] = o.ServerConfigId
	toSerialize["numInstances"] = o.NumInstances
	toSerialize["autoScalerEnabled"] = o.AutoScalerEnabled
	if !IsNil(o.AutoScalerMin) {
		toSerialize["autoScalerMin"] = o.AutoScalerMin
	}
	if !IsNil(o.AutoScalerMax) {
		toSerialize["autoScalerMax"] = o.AutoScalerMax
	}
	toSerialize["status"] = o.Status
	toSerialize["statusMessage"] = o.StatusMessage.Get()
	toSerialize["maintenance"] = o.Maintenance
	toSerialize["inUse"] = o.InUse
	toSerialize["placement"] = o.Placement
	if !IsNil(o.ServerConfig) {
		toSerialize["serverConfig"] = o.ServerConfig
	}
	return toSerialize, nil
}

func (o *AppLocationSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"appId",
		"serverConfigId",
		"numInstances",
		"autoScalerEnabled",
		"status",
		"statusMessage",
		"maintenance",
		"inUse",
		"placement",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppLocationSetting := _AppLocationSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppLocationSetting)

	if err != nil {
		return err
	}

	*o = AppLocationSetting(varAppLocationSetting)

	return err
}

type NullableAppLocationSetting struct {
	value *AppLocationSetting
	isSet bool
}

func (v NullableAppLocationSetting) Get() *AppLocationSetting {
	return v.value
}

func (v *NullableAppLocationSetting) Set(val *AppLocationSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableAppLocationSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableAppLocationSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppLocationSetting(val *AppLocationSetting) *NullableAppLocationSetting {
	return &NullableAppLocationSetting{value: val, isSet: true}
}

func (v NullableAppLocationSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppLocationSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}