/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ResourcePackage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourcePackage{}

// ResourcePackage struct for ResourcePackage
type ResourcePackage struct {
	// The id of the resource package
	Id int32 `json:"id"`
	// The name of the resource package
	Name string `json:"name"`
	// The slug of the resource package
	Slug string `json:"slug"`
	// The type of the resource package
	Type ResourcePackageType `json:"type"`
	// The maximum CPU of the resource package
	CpuLimit float32 `json:"cpuLimit"`
	// The maximum memory in bytes of the resource package
	MemoryLimitBytes int64 `json:"memoryLimitBytes"`
	// The maximum memory in mebibytes (MiB) of the resource package
	MemoryLimitMiB float32 `json:"memoryLimitMiB"`
	// The maximum memory in a human-readable format
	MemoryLimitFileSizeString string `json:"memoryLimitFileSizeString"`
}

type _ResourcePackage ResourcePackage

// NewResourcePackage instantiates a new ResourcePackage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourcePackage(id int32, name string, slug string, type_ ResourcePackageType, cpuLimit float32, memoryLimitBytes int64, memoryLimitMiB float32, memoryLimitFileSizeString string) *ResourcePackage {
	this := ResourcePackage{}
	this.Id = id
	this.Name = name
	this.Slug = slug
	this.Type = type_
	this.CpuLimit = cpuLimit
	this.MemoryLimitBytes = memoryLimitBytes
	this.MemoryLimitMiB = memoryLimitMiB
	this.MemoryLimitFileSizeString = memoryLimitFileSizeString
	return &this
}

// NewResourcePackageWithDefaults instantiates a new ResourcePackage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourcePackageWithDefaults() *ResourcePackage {
	this := ResourcePackage{}
	return &this
}

// GetId returns the Id field value
func (o *ResourcePackage) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourcePackage) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ResourcePackage) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResourcePackage) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *ResourcePackage) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ResourcePackage) SetSlug(v string) {
	o.Slug = v
}

// GetType returns the Type field value
func (o *ResourcePackage) GetType() ResourcePackageType {
	if o == nil {
		var ret ResourcePackageType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetTypeOk() (*ResourcePackageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResourcePackage) SetType(v ResourcePackageType) {
	o.Type = v
}

// GetCpuLimit returns the CpuLimit field value
func (o *ResourcePackage) GetCpuLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CpuLimit
}

// GetCpuLimitOk returns a tuple with the CpuLimit field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetCpuLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuLimit, true
}

// SetCpuLimit sets field value
func (o *ResourcePackage) SetCpuLimit(v float32) {
	o.CpuLimit = v
}

// GetMemoryLimitBytes returns the MemoryLimitBytes field value
func (o *ResourcePackage) GetMemoryLimitBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MemoryLimitBytes
}

// GetMemoryLimitBytesOk returns a tuple with the MemoryLimitBytes field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetMemoryLimitBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryLimitBytes, true
}

// SetMemoryLimitBytes sets field value
func (o *ResourcePackage) SetMemoryLimitBytes(v int64) {
	o.MemoryLimitBytes = v
}

// GetMemoryLimitMiB returns the MemoryLimitMiB field value
func (o *ResourcePackage) GetMemoryLimitMiB() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MemoryLimitMiB
}

// GetMemoryLimitMiBOk returns a tuple with the MemoryLimitMiB field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetMemoryLimitMiBOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryLimitMiB, true
}

// SetMemoryLimitMiB sets field value
func (o *ResourcePackage) SetMemoryLimitMiB(v float32) {
	o.MemoryLimitMiB = v
}

// GetMemoryLimitFileSizeString returns the MemoryLimitFileSizeString field value
func (o *ResourcePackage) GetMemoryLimitFileSizeString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryLimitFileSizeString
}

// GetMemoryLimitFileSizeStringOk returns a tuple with the MemoryLimitFileSizeString field value
// and a boolean to check if the value has been set.
func (o *ResourcePackage) GetMemoryLimitFileSizeStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryLimitFileSizeString, true
}

// SetMemoryLimitFileSizeString sets field value
func (o *ResourcePackage) SetMemoryLimitFileSizeString(v string) {
	o.MemoryLimitFileSizeString = v
}

func (o ResourcePackage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourcePackage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	toSerialize["type"] = o.Type
	toSerialize["cpuLimit"] = o.CpuLimit
	toSerialize["memoryLimitBytes"] = o.MemoryLimitBytes
	toSerialize["memoryLimitMiB"] = o.MemoryLimitMiB
	toSerialize["memoryLimitFileSizeString"] = o.MemoryLimitFileSizeString
	return toSerialize, nil
}

func (o *ResourcePackage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"slug",
		"type",
		"cpuLimit",
		"memoryLimitBytes",
		"memoryLimitMiB",
		"memoryLimitFileSizeString",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourcePackage := _ResourcePackage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourcePackage)

	if err != nil {
		return err
	}

	*o = ResourcePackage(varResourcePackage)

	return err
}

type NullableResourcePackage struct {
	value *ResourcePackage
	isSet bool
}

func (v NullableResourcePackage) Get() *ResourcePackage {
	return v.value
}

func (v *NullableResourcePackage) Set(val *ResourcePackage) {
	v.value = val
	v.isSet = true
}

func (v NullableResourcePackage) IsSet() bool {
	return v.isSet
}

func (v *NullableResourcePackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourcePackage(val *ResourcePackage) *NullableResourcePackage {
	return &NullableResourcePackage{value: val, isSet: true}
}

func (v NullableResourcePackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourcePackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}