/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// Architecture the model 'Architecture'
type Architecture string

// List of Architecture
const (
	ARCHITECTURE_X86_64 Architecture = "x86_64"
)

// All allowed values of Architecture enum
var AllowedArchitectureEnumValues = []Architecture{
	"x86_64",
}

func (v *Architecture) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Architecture(value)
	for _, existing := range AllowedArchitectureEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Architecture", value)
}

// NewArchitectureFromValue returns a pointer to a valid Architecture
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewArchitectureFromValue(v string) (*Architecture, error) {
	ev := Architecture(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Architecture: valid values are %v", v, AllowedArchitectureEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Architecture) IsValid() bool {
	for _, existing := range AllowedArchitectureEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Architecture value
func (v Architecture) Ptr() *Architecture {
	return &v
}

type NullableArchitecture struct {
	value *Architecture
	isSet bool
}

func (v NullableArchitecture) Get() *Architecture {
	return v.value
}

func (v *NullableArchitecture) Set(val *Architecture) {
	v.value = val
	v.isSet = true
}

func (v NullableArchitecture) IsSet() bool {
	return v.isSet
}

func (v *NullableArchitecture) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchitecture(val *Architecture) *NullableArchitecture {
	return &NullableArchitecture{value: val, isSet: true}
}

func (v NullableArchitecture) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchitecture) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}