/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// EnvironmentVariableType the model 'EnvironmentVariableType'
type EnvironmentVariableType string

// List of EnvironmentVariableType
const (
	ENVIRONMENTVARIABLETYPE_STATIC EnvironmentVariableType = "static"
	ENVIRONMENTVARIABLETYPE_SYSTEM EnvironmentVariableType = "system"
	ENVIRONMENTVARIABLETYPE_PORT   EnvironmentVariableType = "port"
)

// All allowed values of EnvironmentVariableType enum
var AllowedEnvironmentVariableTypeEnumValues = []EnvironmentVariableType{
	"static",
	"system",
	"port",
}

func (v *EnvironmentVariableType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnvironmentVariableType(value)
	for _, existing := range AllowedEnvironmentVariableTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnvironmentVariableType", value)
}

// NewEnvironmentVariableTypeFromValue returns a pointer to a valid EnvironmentVariableType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnvironmentVariableTypeFromValue(v string) (*EnvironmentVariableType, error) {
	ev := EnvironmentVariableType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnvironmentVariableType: valid values are %v", v, AllowedEnvironmentVariableTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnvironmentVariableType) IsValid() bool {
	for _, existing := range AllowedEnvironmentVariableTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnvironmentVariableType value
func (v EnvironmentVariableType) Ptr() *EnvironmentVariableType {
	return &v
}

type NullableEnvironmentVariableType struct {
	value *EnvironmentVariableType
	isSet bool
}

func (v NullableEnvironmentVariableType) Get() *EnvironmentVariableType {
	return v.value
}

func (v *NullableEnvironmentVariableType) Set(val *EnvironmentVariableType) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentVariableType) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentVariableType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentVariableType(val *EnvironmentVariableType) *NullableEnvironmentVariableType {
	return &NullableEnvironmentVariableType{value: val, isSet: true}
}

func (v NullableEnvironmentVariableType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentVariableType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}