/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// OperatingSystem the model 'OperatingSystem'
type OperatingSystem string

// List of OperatingSystem
const (
	OPERATINGSYSTEM_WINDOWS OperatingSystem = "windows"
	OPERATINGSYSTEM_LINUX   OperatingSystem = "linux"
)

// All allowed values of OperatingSystem enum
var AllowedOperatingSystemEnumValues = []OperatingSystem{
	"windows",
	"linux",
}

func (v *OperatingSystem) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OperatingSystem(value)
	for _, existing := range AllowedOperatingSystemEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OperatingSystem", value)
}

// NewOperatingSystemFromValue returns a pointer to a valid OperatingSystem
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOperatingSystemFromValue(v string) (*OperatingSystem, error) {
	ev := OperatingSystem(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OperatingSystem: valid values are %v", v, AllowedOperatingSystemEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OperatingSystem) IsValid() bool {
	for _, existing := range AllowedOperatingSystemEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OperatingSystem value
func (v OperatingSystem) Ptr() *OperatingSystem {
	return &v
}

type NullableOperatingSystem struct {
	value *OperatingSystem
	isSet bool
}

func (v NullableOperatingSystem) Get() *OperatingSystem {
	return v.value
}

func (v *NullableOperatingSystem) Set(val *OperatingSystem) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatingSystem) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatingSystem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatingSystem(val *OperatingSystem) *NullableOperatingSystem {
	return &NullableOperatingSystem{value: val, isSet: true}
}

func (v NullableOperatingSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatingSystem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}