/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DockerRegistry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerRegistry{}

// DockerRegistry struct for DockerRegistry
type DockerRegistry struct {
	// The ID of the registry
	Id int32 `json:"id"`
	// The type of the registry
	Type DockerRegistryType `json:"type"`
	// The name of the registry
	Name string `json:"name"`
	// The username to use for authentication
	Username NullableString `json:"username"`
	// The password to use for authentication
	Password NullableString `json:"password"`
	// The URL of the registry
	Url string `json:"url"`
	// The access token to use for authentication
	AccessToken NullableString `json:"accessToken"`
	// The URL of the instance
	InstanceUrl NullableString `json:"instanceUrl"`
	// Whether or not the registry is user-owned or organization-owned
	Organization bool `json:"organization"`
	// AWS access key ID
	AwsAccessKey NullableString `json:"awsAccessKey"`
	// AWS secret access key
	AwsSecretAccessKey NullableString `json:"awsSecretAccessKey"`
}

type _DockerRegistry DockerRegistry

// NewDockerRegistry instantiates a new DockerRegistry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerRegistry(id int32, type_ DockerRegistryType, name string, username NullableString, password NullableString, url string, accessToken NullableString, instanceUrl NullableString, organization bool, awsAccessKey NullableString, awsSecretAccessKey NullableString) *DockerRegistry {
	this := DockerRegistry{}
	this.Id = id
	this.Type = type_
	this.Name = name
	this.Username = username
	this.Password = password
	this.Url = url
	this.AccessToken = accessToken
	this.InstanceUrl = instanceUrl
	this.Organization = organization
	this.AwsAccessKey = awsAccessKey
	this.AwsSecretAccessKey = awsSecretAccessKey
	return &this
}

// NewDockerRegistryWithDefaults instantiates a new DockerRegistry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerRegistryWithDefaults() *DockerRegistry {
	this := DockerRegistry{}
	return &this
}

// GetId returns the Id field value
func (o *DockerRegistry) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DockerRegistry) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DockerRegistry) SetId(v int32) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DockerRegistry) GetType() DockerRegistryType {
	if o == nil {
		var ret DockerRegistryType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DockerRegistry) GetTypeOk() (*DockerRegistryType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DockerRegistry) SetType(v DockerRegistryType) {
	o.Type = v
}

// GetName returns the Name field value
func (o *DockerRegistry) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DockerRegistry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DockerRegistry) SetName(v string) {
	o.Name = v
}

// GetUsername returns the Username field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DockerRegistry) GetUsername() string {
	if o == nil || o.Username.Get() == nil {
		var ret string
		return ret
	}

	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistry) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// SetUsername sets field value
func (o *DockerRegistry) SetUsername(v string) {
	o.Username.Set(&v)
}

// GetPassword returns the Password field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DockerRegistry) GetPassword() string {
	if o == nil || o.Password.Get() == nil {
		var ret string
		return ret
	}

	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistry) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// SetPassword sets field value
func (o *DockerRegistry) SetPassword(v string) {
	o.Password.Set(&v)
}

// GetUrl returns the Url field value
func (o *DockerRegistry) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DockerRegistry) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DockerRegistry) SetUrl(v string) {
	o.Url = v
}

// GetAccessToken returns the AccessToken field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DockerRegistry) GetAccessToken() string {
	if o == nil || o.AccessToken.Get() == nil {
		var ret string
		return ret
	}

	return *o.AccessToken.Get()
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistry) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessToken.Get(), o.AccessToken.IsSet()
}

// SetAccessToken sets field value
func (o *DockerRegistry) SetAccessToken(v string) {
	o.AccessToken.Set(&v)
}

// GetInstanceUrl returns the InstanceUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DockerRegistry) GetInstanceUrl() string {
	if o == nil || o.InstanceUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.InstanceUrl.Get()
}

// GetInstanceUrlOk returns a tuple with the InstanceUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistry) GetInstanceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstanceUrl.Get(), o.InstanceUrl.IsSet()
}

// SetInstanceUrl sets field value
func (o *DockerRegistry) SetInstanceUrl(v string) {
	o.InstanceUrl.Set(&v)
}

// GetOrganization returns the Organization field value
func (o *DockerRegistry) GetOrganization() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *DockerRegistry) GetOrganizationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *DockerRegistry) SetOrganization(v bool) {
	o.Organization = v
}

// GetAwsAccessKey returns the AwsAccessKey field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DockerRegistry) GetAwsAccessKey() string {
	if o == nil || o.AwsAccessKey.Get() == nil {
		var ret string
		return ret
	}

	return *o.AwsAccessKey.Get()
}

// GetAwsAccessKeyOk returns a tuple with the AwsAccessKey field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistry) GetAwsAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsAccessKey.Get(), o.AwsAccessKey.IsSet()
}

// SetAwsAccessKey sets field value
func (o *DockerRegistry) SetAwsAccessKey(v string) {
	o.AwsAccessKey.Set(&v)
}

// GetAwsSecretAccessKey returns the AwsSecretAccessKey field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DockerRegistry) GetAwsSecretAccessKey() string {
	if o == nil || o.AwsSecretAccessKey.Get() == nil {
		var ret string
		return ret
	}

	return *o.AwsSecretAccessKey.Get()
}

// GetAwsSecretAccessKeyOk returns a tuple with the AwsSecretAccessKey field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistry) GetAwsSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsSecretAccessKey.Get(), o.AwsSecretAccessKey.IsSet()
}

// SetAwsSecretAccessKey sets field value
func (o *DockerRegistry) SetAwsSecretAccessKey(v string) {
	o.AwsSecretAccessKey.Set(&v)
}

func (o DockerRegistry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerRegistry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["username"] = o.Username.Get()
	toSerialize["password"] = o.Password.Get()
	toSerialize["url"] = o.Url
	toSerialize["accessToken"] = o.AccessToken.Get()
	toSerialize["instanceUrl"] = o.InstanceUrl.Get()
	toSerialize["organization"] = o.Organization
	toSerialize["awsAccessKey"] = o.AwsAccessKey.Get()
	toSerialize["awsSecretAccessKey"] = o.AwsSecretAccessKey.Get()
	return toSerialize, nil
}

func (o *DockerRegistry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"name",
		"username",
		"password",
		"url",
		"accessToken",
		"instanceUrl",
		"organization",
		"awsAccessKey",
		"awsSecretAccessKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerRegistry := _DockerRegistry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerRegistry)

	if err != nil {
		return err
	}

	*o = DockerRegistry(varDockerRegistry)

	return err
}

type NullableDockerRegistry struct {
	value *DockerRegistry
	isSet bool
}

func (v NullableDockerRegistry) Get() *DockerRegistry {
	return v.value
}

func (v *NullableDockerRegistry) Set(val *DockerRegistry) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerRegistry) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerRegistry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerRegistry(val *DockerRegistry) *NullableDockerRegistry {
	return &NullableDockerRegistry{value: val, isSet: true}
}

func (v NullableDockerRegistry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerRegistry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}