/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BackupDownload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupDownload{}

// BackupDownload struct for BackupDownload
type BackupDownload struct {
	// The url where the file is available
	Url string `json:"url"`
	// After this date the link is no longer valid
	ValidUntil time.Time `json:"validUntil"`
}

type _BackupDownload BackupDownload

// NewBackupDownload instantiates a new BackupDownload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupDownload(url string, validUntil time.Time) *BackupDownload {
	this := BackupDownload{}
	this.Url = url
	this.ValidUntil = validUntil
	return &this
}

// NewBackupDownloadWithDefaults instantiates a new BackupDownload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupDownloadWithDefaults() *BackupDownload {
	this := BackupDownload{}
	return &this
}

// GetUrl returns the Url field value
func (o *BackupDownload) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *BackupDownload) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *BackupDownload) SetUrl(v string) {
	o.Url = v
}

// GetValidUntil returns the ValidUntil field value
func (o *BackupDownload) GetValidUntil() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidUntil
}

// GetValidUntilOk returns a tuple with the ValidUntil field value
// and a boolean to check if the value has been set.
func (o *BackupDownload) GetValidUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidUntil, true
}

// SetValidUntil sets field value
func (o *BackupDownload) SetValidUntil(v time.Time) {
	o.ValidUntil = v
}

func (o BackupDownload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupDownload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["validUntil"] = o.ValidUntil
	return toSerialize, nil
}

func (o *BackupDownload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"validUntil",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupDownload := _BackupDownload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupDownload)

	if err != nil {
		return err
	}

	*o = BackupDownload(varBackupDownload)

	return err
}

type NullableBackupDownload struct {
	value *BackupDownload
	isSet bool
}

func (v NullableBackupDownload) Get() *BackupDownload {
	return v.value
}

func (v *NullableBackupDownload) Set(val *BackupDownload) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupDownload) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupDownload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupDownload(val *BackupDownload) *NullableBackupDownload {
	return &NullableBackupDownload{value: val, isSet: true}
}

func (v NullableBackupDownload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupDownload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}