/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetAppLocationSettings200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppLocationSettings200ResponseMeta{}

// GetAppLocationSettings200ResponseMeta struct for GetAppLocationSettings200ResponseMeta
type GetAppLocationSettings200ResponseMeta struct {
	CurrentPage int32         `json:"current_page"`
	From        NullableInt32 `json:"from"`
	LastPage    int32         `json:"last_page"`
	// Generated paginator links.
	Links []GetAppLocationSettings200ResponseMetaLinksInner `json:"links"`
	// Base path for paginator generated URLs.
	Path NullableString `json:"path"`
	// Number of items shown per page.
	PerPage int32 `json:"per_page"`
	// Number of the last item in the slice.
	To NullableInt32 `json:"to"`
	// Total number of items being paginated.
	Total int32 `json:"total"`
}

type _GetAppLocationSettings200ResponseMeta GetAppLocationSettings200ResponseMeta

// NewGetAppLocationSettings200ResponseMeta instantiates a new GetAppLocationSettings200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppLocationSettings200ResponseMeta(currentPage int32, from NullableInt32, lastPage int32, links []GetAppLocationSettings200ResponseMetaLinksInner, path NullableString, perPage int32, to NullableInt32, total int32) *GetAppLocationSettings200ResponseMeta {
	this := GetAppLocationSettings200ResponseMeta{}
	this.CurrentPage = currentPage
	this.From = from
	this.LastPage = lastPage
	this.Links = links
	this.Path = path
	this.PerPage = perPage
	this.To = to
	this.Total = total
	return &this
}

// NewGetAppLocationSettings200ResponseMetaWithDefaults instantiates a new GetAppLocationSettings200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppLocationSettings200ResponseMetaWithDefaults() *GetAppLocationSettings200ResponseMeta {
	this := GetAppLocationSettings200ResponseMeta{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value
func (o *GetAppLocationSettings200ResponseMeta) GetCurrentPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value
// and a boolean to check if the value has been set.
func (o *GetAppLocationSettings200ResponseMeta) GetCurrentPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPage, true
}

// SetCurrentPage sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetCurrentPage(v int32) {
	o.CurrentPage = v
}

// GetFrom returns the From field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *GetAppLocationSettings200ResponseMeta) GetFrom() int32 {
	if o == nil || o.From.Get() == nil {
		var ret int32
		return ret
	}

	return *o.From.Get()
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppLocationSettings200ResponseMeta) GetFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.From.Get(), o.From.IsSet()
}

// SetFrom sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetFrom(v int32) {
	o.From.Set(&v)
}

// GetLastPage returns the LastPage field value
func (o *GetAppLocationSettings200ResponseMeta) GetLastPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value
// and a boolean to check if the value has been set.
func (o *GetAppLocationSettings200ResponseMeta) GetLastPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastPage, true
}

// SetLastPage sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetLastPage(v int32) {
	o.LastPage = v
}

// GetLinks returns the Links field value
func (o *GetAppLocationSettings200ResponseMeta) GetLinks() []GetAppLocationSettings200ResponseMetaLinksInner {
	if o == nil {
		var ret []GetAppLocationSettings200ResponseMetaLinksInner
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetAppLocationSettings200ResponseMeta) GetLinksOk() ([]GetAppLocationSettings200ResponseMetaLinksInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Links, true
}

// SetLinks sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetLinks(v []GetAppLocationSettings200ResponseMetaLinksInner) {
	o.Links = v
}

// GetPath returns the Path field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetAppLocationSettings200ResponseMeta) GetPath() string {
	if o == nil || o.Path.Get() == nil {
		var ret string
		return ret
	}

	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppLocationSettings200ResponseMeta) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// SetPath sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetPath(v string) {
	o.Path.Set(&v)
}

// GetPerPage returns the PerPage field value
func (o *GetAppLocationSettings200ResponseMeta) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *GetAppLocationSettings200ResponseMeta) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetPerPage(v int32) {
	o.PerPage = v
}

// GetTo returns the To field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *GetAppLocationSettings200ResponseMeta) GetTo() int32 {
	if o == nil || o.To.Get() == nil {
		var ret int32
		return ret
	}

	return *o.To.Get()
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppLocationSettings200ResponseMeta) GetToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.To.Get(), o.To.IsSet()
}

// SetTo sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetTo(v int32) {
	o.To.Set(&v)
}

// GetTotal returns the Total field value
func (o *GetAppLocationSettings200ResponseMeta) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetAppLocationSettings200ResponseMeta) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetAppLocationSettings200ResponseMeta) SetTotal(v int32) {
	o.Total = v
}

func (o GetAppLocationSettings200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppLocationSettings200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current_page"] = o.CurrentPage
	toSerialize["from"] = o.From.Get()
	toSerialize["last_page"] = o.LastPage
	toSerialize["links"] = o.Links
	toSerialize["path"] = o.Path.Get()
	toSerialize["per_page"] = o.PerPage
	toSerialize["to"] = o.To.Get()
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *GetAppLocationSettings200ResponseMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current_page",
		"from",
		"last_page",
		"links",
		"path",
		"per_page",
		"to",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAppLocationSettings200ResponseMeta := _GetAppLocationSettings200ResponseMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAppLocationSettings200ResponseMeta)

	if err != nil {
		return err
	}

	*o = GetAppLocationSettings200ResponseMeta(varGetAppLocationSettings200ResponseMeta)

	return err
}

type NullableGetAppLocationSettings200ResponseMeta struct {
	value *GetAppLocationSettings200ResponseMeta
	isSet bool
}

func (v NullableGetAppLocationSettings200ResponseMeta) Get() *GetAppLocationSettings200ResponseMeta {
	return v.value
}

func (v *NullableGetAppLocationSettings200ResponseMeta) Set(val *GetAppLocationSettings200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppLocationSettings200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppLocationSettings200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppLocationSettings200ResponseMeta(val *GetAppLocationSettings200ResponseMeta) *NullableGetAppLocationSettings200ResponseMeta {
	return &NullableGetAppLocationSettings200ResponseMeta{value: val, isSet: true}
}

func (v NullableGetAppLocationSettings200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppLocationSettings200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}