/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PortDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortDefinition{}

// PortDefinition struct for PortDefinition
type PortDefinition struct {
	// The name of the server config
	Name string `json:"name"`
	// The protocols to expose
	Protocols []Protocol `json:"protocols"`
	// The port to expose
	TargetPort int32 `json:"targetPort"`
}

type _PortDefinition PortDefinition

// NewPortDefinition instantiates a new PortDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortDefinition(name string, protocols []Protocol, targetPort int32) *PortDefinition {
	this := PortDefinition{}
	this.Name = name
	this.Protocols = protocols
	this.TargetPort = targetPort
	return &this
}

// NewPortDefinitionWithDefaults instantiates a new PortDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortDefinitionWithDefaults() *PortDefinition {
	this := PortDefinition{}
	return &this
}

// GetName returns the Name field value
func (o *PortDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PortDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PortDefinition) SetName(v string) {
	o.Name = v
}

// GetProtocols returns the Protocols field value
func (o *PortDefinition) GetProtocols() []Protocol {
	if o == nil {
		var ret []Protocol
		return ret
	}

	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value
// and a boolean to check if the value has been set.
func (o *PortDefinition) GetProtocolsOk() ([]Protocol, bool) {
	if o == nil {
		return nil, false
	}
	return o.Protocols, true
}

// SetProtocols sets field value
func (o *PortDefinition) SetProtocols(v []Protocol) {
	o.Protocols = v
}

// GetTargetPort returns the TargetPort field value
func (o *PortDefinition) GetTargetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetPort
}

// GetTargetPortOk returns a tuple with the TargetPort field value
// and a boolean to check if the value has been set.
func (o *PortDefinition) GetTargetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPort, true
}

// SetTargetPort sets field value
func (o *PortDefinition) SetTargetPort(v int32) {
	o.TargetPort = v
}

func (o PortDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["protocols"] = o.Protocols
	toSerialize["targetPort"] = o.TargetPort
	return toSerialize, nil
}

func (o *PortDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"protocols",
		"targetPort",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPortDefinition := _PortDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPortDefinition)

	if err != nil {
		return err
	}

	*o = PortDefinition(varPortDefinition)

	return err
}

type NullablePortDefinition struct {
	value *PortDefinition
	isSet bool
}

func (v NullablePortDefinition) Get() *PortDefinition {
	return v.value
}

func (v *NullablePortDefinition) Set(val *PortDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullablePortDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullablePortDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortDefinition(val *PortDefinition) *NullablePortDefinition {
	return &NullablePortDefinition{value: val, isSet: true}
}

func (v NullablePortDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}