/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Binary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Binary{}

// Binary struct for Binary
type Binary struct {
	// The id of the binary
	Id int32 `json:"id"`
	// The app id of the binary
	AppId int32 `json:"appId"`
	// The app id of the binary
	Name string `json:"name"`
	// The version of the binary
	Version string `json:"version"`
	// The type of the binary
	Type BinaryType `json:"type"`
	// The operating system of the binary
	Os OperatingSystem `json:"os"`
	// Indicates if the binary is under maintenance
	Maintenance bool `json:"maintenance"`
	// The current status of the binary
	Status BinaryStatus `json:"status"`
	// An optional message returned by the build process
	StatusMessage NullableString `json:"statusMessage"`
	// The current progress percentage of the image build (0-100). Only present for binaries of type steam.
	Progress NullableFloat32 `json:"progress,omitempty"`
	// A message describing the current build step. Only present for binaries of type steam.
	ProgressMessage NullableString `json:"progressMessage,omitempty"`
	// Indicates whether the binary is currently in use
	InUse bool `json:"inUse"`
	// The docker image of the binary
	DockerImage *DockerImage `json:"dockerImage,omitempty"`
	// The steam of the binary
	Steam *Steam `json:"steam,omitempty"`
}

type _Binary Binary

// NewBinary instantiates a new Binary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBinary(id int32, appId int32, name string, version string, type_ BinaryType, os OperatingSystem, maintenance bool, status BinaryStatus, statusMessage NullableString, inUse bool) *Binary {
	this := Binary{}
	this.Id = id
	this.AppId = appId
	this.Name = name
	this.Version = version
	this.Type = type_
	this.Os = os
	this.Maintenance = maintenance
	this.Status = status
	this.StatusMessage = statusMessage
	this.InUse = inUse
	return &this
}

// NewBinaryWithDefaults instantiates a new Binary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBinaryWithDefaults() *Binary {
	this := Binary{}
	return &this
}

// GetId returns the Id field value
func (o *Binary) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Binary) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Binary) SetId(v int32) {
	o.Id = v
}

// GetAppId returns the AppId field value
func (o *Binary) GetAppId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *Binary) GetAppIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *Binary) SetAppId(v int32) {
	o.AppId = v
}

// GetName returns the Name field value
func (o *Binary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Binary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Binary) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *Binary) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *Binary) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *Binary) SetVersion(v string) {
	o.Version = v
}

// GetType returns the Type field value
func (o *Binary) GetType() BinaryType {
	if o == nil {
		var ret BinaryType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Binary) GetTypeOk() (*BinaryType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Binary) SetType(v BinaryType) {
	o.Type = v
}

// GetOs returns the Os field value
func (o *Binary) GetOs() OperatingSystem {
	if o == nil {
		var ret OperatingSystem
		return ret
	}

	return o.Os
}

// GetOsOk returns a tuple with the Os field value
// and a boolean to check if the value has been set.
func (o *Binary) GetOsOk() (*OperatingSystem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Os, true
}

// SetOs sets field value
func (o *Binary) SetOs(v OperatingSystem) {
	o.Os = v
}

// GetMaintenance returns the Maintenance field value
func (o *Binary) GetMaintenance() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Maintenance
}

// GetMaintenanceOk returns a tuple with the Maintenance field value
// and a boolean to check if the value has been set.
func (o *Binary) GetMaintenanceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Maintenance, true
}

// SetMaintenance sets field value
func (o *Binary) SetMaintenance(v bool) {
	o.Maintenance = v
}

// GetStatus returns the Status field value
func (o *Binary) GetStatus() BinaryStatus {
	if o == nil {
		var ret BinaryStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Binary) GetStatusOk() (*BinaryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Binary) SetStatus(v BinaryStatus) {
	o.Status = v
}

// GetStatusMessage returns the StatusMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Binary) GetStatusMessage() string {
	if o == nil || o.StatusMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.StatusMessage.Get()
}

// GetStatusMessageOk returns a tuple with the StatusMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Binary) GetStatusMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusMessage.Get(), o.StatusMessage.IsSet()
}

// SetStatusMessage sets field value
func (o *Binary) SetStatusMessage(v string) {
	o.StatusMessage.Set(&v)
}

// GetProgress returns the Progress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Binary) GetProgress() float32 {
	if o == nil || IsNil(o.Progress.Get()) {
		var ret float32
		return ret
	}
	return *o.Progress.Get()
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Binary) GetProgressOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Progress.Get(), o.Progress.IsSet()
}

// HasProgress returns a boolean if a field has been set.
func (o *Binary) HasProgress() bool {
	if o != nil && o.Progress.IsSet() {
		return true
	}

	return false
}

// SetProgress gets a reference to the given NullableFloat32 and assigns it to the Progress field.
func (o *Binary) SetProgress(v float32) {
	o.Progress.Set(&v)
}
// SetProgressNil sets the value for Progress to be an explicit nil
func (o *Binary) SetProgressNil() {
	o.Progress.Set(nil)
}

// UnsetProgress ensures that no value is present for Progress, not even an explicit nil
func (o *Binary) UnsetProgress() {
	o.Progress.Unset()
}

// GetProgressMessage returns the ProgressMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Binary) GetProgressMessage() string {
	if o == nil || IsNil(o.ProgressMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ProgressMessage.Get()
}

// GetProgressMessageOk returns a tuple with the ProgressMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Binary) GetProgressMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProgressMessage.Get(), o.ProgressMessage.IsSet()
}

// HasProgressMessage returns a boolean if a field has been set.
func (o *Binary) HasProgressMessage() bool {
	if o != nil && o.ProgressMessage.IsSet() {
		return true
	}

	return false
}

// SetProgressMessage gets a reference to the given NullableString and assigns it to the ProgressMessage field.
func (o *Binary) SetProgressMessage(v string) {
	o.ProgressMessage.Set(&v)
}
// SetProgressMessageNil sets the value for ProgressMessage to be an explicit nil
func (o *Binary) SetProgressMessageNil() {
	o.ProgressMessage.Set(nil)
}

// UnsetProgressMessage ensures that no value is present for ProgressMessage, not even an explicit nil
func (o *Binary) UnsetProgressMessage() {
	o.ProgressMessage.Unset()
}

// GetInUse returns the InUse field value
func (o *Binary) GetInUse() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InUse
}

// GetInUseOk returns a tuple with the InUse field value
// and a boolean to check if the value has been set.
func (o *Binary) GetInUseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InUse, true
}

// SetInUse sets field value
func (o *Binary) SetInUse(v bool) {
	o.InUse = v
}

// GetDockerImage returns the DockerImage field value if set, zero value otherwise.
func (o *Binary) GetDockerImage() DockerImage {
	if o == nil || IsNil(o.DockerImage) {
		var ret DockerImage
		return ret
	}
	return *o.DockerImage
}

// GetDockerImageOk returns a tuple with the DockerImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Binary) GetDockerImageOk() (*DockerImage, bool) {
	if o == nil || IsNil(o.DockerImage) {
		return nil, false
	}
	return o.DockerImage, true
}

// HasDockerImage returns a boolean if a field has been set.
func (o *Binary) HasDockerImage() bool {
	if o != nil && !IsNil(o.DockerImage) {
		return true
	}

	return false
}

// SetDockerImage gets a reference to the given DockerImage and assigns it to the DockerImage field.
func (o *Binary) SetDockerImage(v DockerImage) {
	o.DockerImage = &v
}

// GetSteam returns the Steam field value if set, zero value otherwise.
func (o *Binary) GetSteam() Steam {
	if o == nil || IsNil(o.Steam) {
		var ret Steam
		return ret
	}
	return *o.Steam
}

// GetSteamOk returns a tuple with the Steam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Binary) GetSteamOk() (*Steam, bool) {
	if o == nil || IsNil(o.Steam) {
		return nil, false
	}
	return o.Steam, true
}

// HasSteam returns a boolean if a field has been set.
func (o *Binary) HasSteam() bool {
	if o != nil && !IsNil(o.Steam) {
		return true
	}

	return false
}

// SetSteam gets a reference to the given Steam and assigns it to the Steam field.
func (o *Binary) SetSteam(v Steam) {
	o.Steam = &v
}

func (o Binary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Binary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["appId"] = o.AppId
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["type"] = o.Type
	toSerialize["os"] = o.Os
	toSerialize["maintenance"] = o.Maintenance
	toSerialize["status"] = o.Status
	toSerialize["statusMessage"] = o.StatusMessage.Get()
	if o.Progress.IsSet() {
		toSerialize["progress"] = o.Progress.Get()
	}
	if o.ProgressMessage.IsSet() {
		toSerialize["progressMessage"] = o.ProgressMessage.Get()
	}
	toSerialize["inUse"] = o.InUse
	if !IsNil(o.DockerImage) {
		toSerialize["dockerImage"] = o.DockerImage
	}
	if !IsNil(o.Steam) {
		toSerialize["steam"] = o.Steam
	}
	return toSerialize, nil
}

func (o *Binary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"appId",
		"name",
		"version",
		"type",
		"os",
		"maintenance",
		"status",
		"statusMessage",
		"inUse",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBinary := _Binary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBinary)

	if err != nil {
		return err
	}

	*o = Binary(varBinary)

	return err
}

type NullableBinary struct {
	value *Binary
	isSet bool
}

func (v NullableBinary) Get() *Binary {
	return v.value
}

func (v *NullableBinary) Set(val *Binary) {
	v.value = val
	v.isSet = true
}

func (v NullableBinary) IsSet() bool {
	return v.isSet
}

func (v *NullableBinary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBinary(val *Binary) *NullableBinary {
	return &NullableBinary{value: val, isSet: true}
}

func (v NullableBinary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBinary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}