/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// BinaryStatus the model 'BinaryStatus'
type BinaryStatus string

// List of BinaryStatus
const (
	BINARYSTATUS_PENDING  BinaryStatus = "pending"
	BINARYSTATUS_BUILDING BinaryStatus = "building"
	BINARYSTATUS_DELETING BinaryStatus = "deleting"
	BINARYSTATUS_UPDATING BinaryStatus = "updating"
	BINARYSTATUS_WAITING  BinaryStatus = "waiting"
	BINARYSTATUS_ERROR    BinaryStatus = "error"
	BINARYSTATUS_READY    BinaryStatus = "ready"
)

// All allowed values of BinaryStatus enum
var AllowedBinaryStatusEnumValues = []BinaryStatus{
	"pending",
	"building",
	"deleting",
	"updating",
	"waiting",
	"error",
	"ready",
}

func (v *BinaryStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BinaryStatus(value)
	for _, existing := range AllowedBinaryStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BinaryStatus", value)
}

// NewBinaryStatusFromValue returns a pointer to a valid BinaryStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBinaryStatusFromValue(v string) (*BinaryStatus, error) {
	ev := BinaryStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BinaryStatus: valid values are %v", v, AllowedBinaryStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BinaryStatus) IsValid() bool {
	for _, existing := range AllowedBinaryStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BinaryStatus value
func (v BinaryStatus) Ptr() *BinaryStatus {
	return &v
}

type NullableBinaryStatus struct {
	value *BinaryStatus
	isSet bool
}

func (v NullableBinaryStatus) Get() *BinaryStatus {
	return v.value
}

func (v *NullableBinaryStatus) Set(val *BinaryStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBinaryStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBinaryStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBinaryStatus(val *BinaryStatus) *NullableBinaryStatus {
	return &NullableBinaryStatus{value: val, isSet: true}
}

func (v NullableBinaryStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBinaryStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}