/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TaggedImageMetaData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaggedImageMetaData{}

// TaggedImageMetaData struct for TaggedImageMetaData
type TaggedImageMetaData struct {
	// Whether the data was retrieved from the cache.
	Cached bool `json:"cached"`
	// Timestamp of when the data was last cached.
	CachedAt NullableString `json:"cached_at"`
}

type _TaggedImageMetaData TaggedImageMetaData

// NewTaggedImageMetaData instantiates a new TaggedImageMetaData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaggedImageMetaData(cached bool, cachedAt NullableString) *TaggedImageMetaData {
	this := TaggedImageMetaData{}
	this.Cached = cached
	this.CachedAt = cachedAt
	return &this
}

// NewTaggedImageMetaDataWithDefaults instantiates a new TaggedImageMetaData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaggedImageMetaDataWithDefaults() *TaggedImageMetaData {
	this := TaggedImageMetaData{}
	return &this
}

// GetCached returns the Cached field value
func (o *TaggedImageMetaData) GetCached() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cached
}

// GetCachedOk returns a tuple with the Cached field value
// and a boolean to check if the value has been set.
func (o *TaggedImageMetaData) GetCachedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cached, true
}

// SetCached sets field value
func (o *TaggedImageMetaData) SetCached(v bool) {
	o.Cached = v
}

// GetCachedAt returns the CachedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaggedImageMetaData) GetCachedAt() string {
	if o == nil || o.CachedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CachedAt.Get()
}

// GetCachedAtOk returns a tuple with the CachedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaggedImageMetaData) GetCachedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CachedAt.Get(), o.CachedAt.IsSet()
}

// SetCachedAt sets field value
func (o *TaggedImageMetaData) SetCachedAt(v string) {
	o.CachedAt.Set(&v)
}

func (o TaggedImageMetaData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaggedImageMetaData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cached"] = o.Cached
	toSerialize["cached_at"] = o.CachedAt.Get()
	return toSerialize, nil
}

func (o *TaggedImageMetaData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cached",
		"cached_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaggedImageMetaData := _TaggedImageMetaData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaggedImageMetaData)

	if err != nil {
		return err
	}

	*o = TaggedImageMetaData(varTaggedImageMetaData)

	return err
}

type NullableTaggedImageMetaData struct {
	value *TaggedImageMetaData
	isSet bool
}

func (v NullableTaggedImageMetaData) Get() *TaggedImageMetaData {
	return v.value
}

func (v *NullableTaggedImageMetaData) Set(val *TaggedImageMetaData) {
	v.value = val
	v.isSet = true
}

func (v NullableTaggedImageMetaData) IsSet() bool {
	return v.isSet
}

func (v *NullableTaggedImageMetaData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaggedImageMetaData(val *TaggedImageMetaData) *NullableTaggedImageMetaData {
	return &NullableTaggedImageMetaData{value: val, isSet: true}
}

func (v NullableTaggedImageMetaData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaggedImageMetaData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}