/*
ODIN Fleet API

API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// AppBillingState the model 'AppBillingState'
type AppBillingState string

// List of AppBillingState
const (
	APPBILLINGSTATE_FREE      AppBillingState = "free"
	APPBILLINGSTATE_ACTIVE    AppBillingState = "active"
	APPBILLINGSTATE_CANCELLED AppBillingState = "cancelled"
	APPBILLINGSTATE_INDIE     AppBillingState = "indie"
)

// All allowed values of AppBillingState enum
var AllowedAppBillingStateEnumValues = []AppBillingState{
	"free",
	"active",
	"cancelled",
	"indie",
}

func (v *AppBillingState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppBillingState(value)
	for _, existing := range AllowedAppBillingStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppBillingState", value)
}

// NewAppBillingStateFromValue returns a pointer to a valid AppBillingState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppBillingStateFromValue(v string) (*AppBillingState, error) {
	ev := AppBillingState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppBillingState: valid values are %v", v, AllowedAppBillingStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppBillingState) IsValid() bool {
	for _, existing := range AllowedAppBillingStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppBillingState value
func (v AppBillingState) Ptr() *AppBillingState {
	return &v
}

type NullableAppBillingState struct {
	value *AppBillingState
	isSet bool
}

func (v NullableAppBillingState) Get() *AppBillingState {
	return v.value
}

func (v *NullableAppBillingState) Set(val *AppBillingState) {
	v.value = val
	v.isSet = true
}

func (v NullableAppBillingState) IsSet() bool {
	return v.isSet
}

func (v *NullableAppBillingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppBillingState(val *AppBillingState) *NullableAppBillingState {
	return &NullableAppBillingState{value: val, isSet: true}
}

func (v NullableAppBillingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppBillingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}